language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install build-essential; fi

install:
  - cmake -H./ -BBuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd Build
  - make
  - cd ..

script:
  - cd Build
  - ctest -V